name: "Installation Process Testing"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      HUSKY: 0 # Bypass husky commit hook while running in a GitHub Actions workflow

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: "Install Bun"
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "0.8.1"
      - name: "Install dependencies"
        run: bun install
      - name: "Compile Action"
        run: bun run build
      - name: "Tier CLI Setup Step"
        uses: ./
        with:
          version: "0.12.0"
      - name: "Verify Tier CLI Version"
        run: tier version
      - name: "Push build artifact back to the remote repository"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): adds recent build artifact"
